name: Publish wp-cli-php
on:
  push:
    branches: [ wp-cli-php ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image:
          - wp-cli-php-7.2
          - wp-cli-php-7.4
          - wp-cli-php-8.0
          - wp-cli-php-8.1
          - wp-cli-php-8.2
          - wp-cli-php-8.3
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build ${{ matrix.docker-image }}
        run: make build
        working-directory: ${{ matrix.docker-image }}

      - name: push ${{ matrix.docker-image }}
        run: make push
        working-directory: ${{ matrix.docker-image }}
