name: Publish db-dumper
on:
  push:
    branches: [db-dumper]
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image:
          - db-dumper
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build ${{ matrix.docker-image }}
        run: make build
        working-directory: ${{ matrix.docker-image }}

      - name: push ${{ matrix.docker-image }}
        run: make push
        working-directory: ${{ matrix.docker-image }}
