name: Publish elixir-ubuntu
on:
  push:
    branches: [ elixir-ubuntu ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-image:
          - elixir-ubuntu-24-04
          - elixir-ubuntu-22-04
          - elixir-ubuntu-20-04
          - elixir-ubuntu-18-04
          #- elixir-ubuntu-16-04
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build ${{ matrix.docker-image }}
        run: make build
        working-directory: ${{ matrix.docker-image }}

      - name: push ${{ matrix.docker-image }}
        run: make push
        working-directory: ${{ matrix.docker-image }}
