name: Publish composer-php
on:
  push:
    branches: [composer-php]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image:
          - composer-php-8.1
          - composer-php-8.2
          - composer-php-8.3
    steps:
      - uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        env:
          GHCR_PERSONAL_TOKEN: ${{ secrets.GHCR_PERSONAL_TOKEN }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
        run: |
          echo $GHCR_PERSONAL_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin

      - name: build ${{ matrix.docker-image }}
        run: make build
        working-directory: ${{ matrix.docker-image }}

      - name: push ${{ matrix.docker-image }}
        run: make push
        working-directory: ${{ matrix.docker-image }}
